# Generated by Django 5.1.6 on 2025-04-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('emptied_at', models.DateTimeField()),
                ('fill_level', models.FloatField()),
            ],
        ),
    ]
