# Generated by Django 5.1.6 on 2025-04-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binmodel',
            name='emptied_at',
            field=models.DateTimeField(null=True),
        ),
    ]
