# Generated by Django 5.1.6 on 2025-04-09 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_alter_binmodel_emptied_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinLocationModel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='binmodel',
            name='fill_level',
        ),
        migrations.AddField(
            model_name='binmodel',
            name='bin_url',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='binmodel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='bins.binlocationmodel'),
        ),
    ]
