# Generated by Django 5.1.6 on 2025-04-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0003_binlocationmodel_remove_binmodel_fill_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binlocationmodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
