# Generated by Django 5.1.6 on 2025-04-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0004_alter_binlocationmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='binlocationmodel',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='binlocationmodel',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
