# Generated by Django 5.1.6 on 2025-04-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0005_binlocationmodel_latitude_binlocationmodel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binlocationmodel',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='binlocationmodel',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
