# Generated by Django 5.1.6 on 2025-04-23 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bins", "0007_binmodel_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="binlocationmodel",
            name="date_created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
